name: Main

on:
  schedule:
    - cron: "0 4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
                   
      - name: Run scraper 
        run: python ./etl/reed_scraper.py ./etl/developer_keywords.csv 
        env: 
          REED_API_KEY: ${{ secrets.REED_API_KEY }} 
        
      - name: Upload new jobs to DB 
        run: python ./etl/load_to_db.py 
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      
