name: Main

on:
  schedule:
    - cron: "0 4 * * *"
    
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test Secret
        env: 
          TEST_SECRET: ${{ secret.TEST_ENVIRONMENT_VARIABLE }}
        run: |
          echo "$TEST_ENVIRONMENT_VARIABLE"
      - name: Run scraper 
        env: 
          REED_API_KEY: ${{ secrets.REED_API_KEY }}
        run: |
          python ./etl/reed_scraper.py ./etl/developer_keywords.csv 
        
        
      - name: Upload new jobs to DB 
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python ./etl/load_to_db.py 
        

      
